package com.cg.omts.dao;

public interface IAdminQueryConstants {
	
	String GET_THEATRE_DETAILS = "SELECT * FROM THEATRE";
	
	String ADD_THEATRE = "INSERT INTO THEATRE VALUES(?,?,?,?,?)";
	
	String DELETE_THEATRE = "DELETE FROM THEATRE WHERE THEATREID=?";
	
	String GET_THEATRE_BY_NAME="SELECT * FROM THEATRE WHERE THEATRENAME=?";
	
	String GET_SHOW_DETAILS = "SELECT * FROM SHOWDETAILS";
	
	String ADD_SHOW = "INSERT INTO SHOWDETAILS VALUES(?,?,?,?,?,?,?,?)";
	
	String DELETE_SHOW = "DELETE FROM SHOWDETAILS WHERE SHOWID=?";
	
	String GET_SHOW_BY_NAME="SELECT * FROM SHOWDETAILS WHERE SHOWNAME=?";
	
	String GET_MOVIELENGTH = "SELECT MOVIELENGTH FROM MOVIE WHERE MOVIEID=?";
	
	String GET_MOVIENAME_FROM_MOVIE = "SELECT MOVIENAME FROM MOVIE WHERE MOVIEID=?";
	
	String GET_SCREEN_FROM_MOVIE_AND_THEATRE="SELECT SCREENID,THEATREID FROM SCREEN WHERE THEATREID =(SELECT THEATREID FROM MOVIE WHERE MOVIEID=? AND THEATREID=?)";
	
	String GET_MOVIENAME_BY_FROM_MOVIE = "SELECT MOVIENAME FROM MOVIE WHERE MOVIEID = ?";
}
